
version: '3.7'

services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=consultorio
    volumes:
      - consultorio_pg_data:/postgres:latest

volumes:
  consultorio_pg_data: